name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./target/release/code_engine_rust

  container:
    name: Build Container
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/bun.dockerfile
            image: bun-engine
          - dockerfile: ./docker/dotnet.dockerfile
            image: dotnet-engine
          - dockerfile: ./docker/typescript.dockerfile
            image: typescript-engine
          - dockerfile: ./docker/python.dockerfile
            image: python-engine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to docker registory
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Download executable
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./target/release/
      - name: Make engine executable
        run: chmod +x ./target/release/code_engine_rust
      - name: Lowercase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/${{ matrix.image }}:latest
